name: paragonn-clearplot
version: ${version}
main: net.elicodes.clearplot.Main
author: EliCodes
depend: [FastAsyncWorldEdit, PlotSquared]
load: POSTWORLD
commands:
  clearplot:
    aliases: [cp, limparterreno]